# Generated by Django 4.1.5 on 2023-03-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('dia', models.DateField(verbose_name='Día de actividad')),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', '-title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
    ]
