# Generated by Django 4.1.5 on 2023-03-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_notificationconfig_alter_page_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationconfig',
            name='dia',
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='day',
            field=models.CharField(default='Lunes, Martes', max_length=100, verbose_name='Día de actividad'),
        ),
    ]
