# Generated by Django 4.1.5 on 2023-03-25 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_notificationconfig_dia_notificationconfig_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconfig',
            name='day',
            field=models.CharField(default='', max_length=100, verbose_name='Día de actividad'),
        ),
    ]
